name: Nix CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Nix Build

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Setup Nix GHA Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Nix files are formatted
        run:  nix develop --command bash -c "nixfmt --check flake.nix ./nix/expert.nix"

      - name: Build
        run: nix build .#expert

  deps:
    runs-on: ubuntu-latest
    name: Nix Deps Up-To-Date

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1

      - name: Setup Nix GHA Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Regenerate deps.nix
        run: nix run .#update-deps

      - name: Ensure deps.nix is up to date
        run: |
          if ! git diff --exit-code; then
            echo "::error::deps.nix is out of date. Run 'mix deps.nix' in each app and commit the result."
            exit 1
          fi
